# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e4236257ffeeeec362409393e66ed64f1c0b4ebb80bc64a3d1d40305cb4ea99c66a4497a03cd8b0af5c20c60c83b6725c8ee902b98a999c3effa01147f158bd

test:
  secret_key_base: b127e81a188b7e46f19d1da48355bb57b2c04196e92ed05c8d28b1d1b822d2047a894012dbbd2e0c7e9627a3cd4f7af5ee6cd5e613024ea2170e8ee8b0bfe55e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
